name: cottonbot
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - pip=24.0
  - python=3.10.14
  - pip:
      - discord-py==2.3.2
      - numpy==1.26.4
      - tokenizers==0.22.1
      - torch==2.9.0 --index-url https://download.pytorch.org/whl/cu126
      - torchmetrics==0.11.4
      - transformers==4.57.0
      - accelerate==1.10.1
